### ISSUE TITLE
Update Xamarin SDK Android guide

### ISSUE THREAD

**Issue by aleks42** [adjust/xamarin_sdk#10]
"Xamarin SDK Android guide" doesn't describe integration for Visual Studio and for projects built with  "Xamarin.Forms Portable" template.

**Comment by uerceg** [comment]
Hi @aleks42,

We are prepairing guides for Visual Studio and once done, will be published. No fixed ETA at this moment. Will keep you posted on this issue. 

Cheers

**Comment by aleks42** [comment]
Hello! I have just added adjust SDK to my Xamarin.Forms application (Android). Now I'm not sure, that it works correctly. I have no "Time" and "Retention Rate" tabs in the dashboard. Any news about Xamarin.Forms guide?

**Comment by uerceg** [comment]
Hi @aleks42 

And sorry for the delay. We have tested our SDK in Xamarin.Forms Portable app and everything works just fine. We were following steps for each platform like we have described them in our README.

After you track some things with our SDK, it doesn't get displayed in the dashboard directly and if you are using sandbox environment when testing, you actually need to check for sandbox traffic in the dashboard and not production traffic.

Any luck with this?

Cheers

**Comment by aleks42** [comment]
Yes, thank you, SDK works fine.
But your example is not complete. I did not find tracking events from pcl project example (via DependencyService), "Integrate the SDK into your app" for Visual Studio and nuget package for all platforms.

**Comment by uerceg** [comment]
We have two example apps in the repository, which were pretty much built in Xamarin Studio on Mac OS X (and which we are using these days in Visual Studio for Mac OS X). We didn't upload any instructions or app examples from Visual Studio apps made on Microsoft Windows operating system.

How would you like to see this being part of our repository? Do you think that making example apps in Visual Studio (Forms, PCL) with our SDK integrated in it would be enough?

As far as NuGet package is concerned, we do have official Windows SDK pushed to NuGet, but Xamarin SDK is still not in there. We will add it to our roadmap to make it available in there, but no exact ETA on this at this moment.

**Comment by aleks42** [comment]
Speaking of example, I mean "Xamarin SDK Android guide" [().](https://github.com/adjust/xamarin_sdk/blob/master/doc/android/android.md) Such sections as "Integrate the SDK into your app" contain screenshots of solution explorer and I see GlobalApplication.cs file there. I have no such file when I create new "Blank XAML App (Xamarin.Forms Portable)" project in Visual Studio. I initialize Adjust in MainActivity.cs

Windows SDK NuGet package is ok, but I would like a crossplatform package like newtonsoft.json or sqlite-net-pcl.

**Comment by 2beens** [comment]
@aleks42 We support our Xamarin SDK integration through NuGet, so you can try that:
For iOS:
https://www.nuget.org/packages/AdjustSdk.Xamarin.iOS/
For Android:
https://www.nuget.org/packages/AdjustSdk.Xamarin.Android/

If you need more help, feel free to reopen the issue.
