### ISSUE TITLE
release 4.20

### ISSUE THREAD

**Issue by fareshan** [adjust/xamarin_sdk#25]
Hello,
I received an email from your support telling me to upgrade to version 4.20 in order to continue detecting Installs
But it seems that you did not release it for Xamarin!
Are you planning to do it?

**Comment by uerceg** [comment]
Hi @fareshan 

That referred to native Android SDK version which are currently at 4.20.0. Xamarin SDK still didn't pick up that update and is currently at 4.18.0. Having any version of the Xamarin SDK which underneath includes native Android SDK v4.12.0 or higher is what you should make sure you have. In case of Xamarin SDK, it's v4.12.0 or above. Of course, if you are already updating, we always recommend you to use latest available Xamarin SDK version at the moment of update.

In case you have any further questions, feel free to ping.

Cheers
