### ISSUE TITLE
Adjust iOS bindings - AdjustConfig null

### ISSUE THREAD

**Issue by kvntzn** [adjust/xamarin_sdk#30]
```
using AdjustBindingsiOS;

public override bool FinishedLaunching(UIApplication app, NSDictionary options)
 {
            string yourAppToken = "{token}";
            string environment = AdjustConfig.EnvironmentSandbox;
            var config = ADJConfig.ConfigWithAppToken(yourAppToken, environment);
            config.LogLevel = ADJLogLevel.Verbose;

            Adjust.AppDidLaunch(config);

          //Other code...
 }

```
Already added -gcc_flags "-ObjC" as an mtouch arguments on iOS Build. Adjust bindings were recognized but adjust config returns null.
I am using AdjustSdk.Xamarin.iOS v4.23.1

![image](https://user-images.githubusercontent.com/29770932/99670694-e2561a80-2aab-11eb-8f88-4df4994e55a6.png)

**Comment by uerceg** [comment]
Hi @kvntzn 

Thanks for reporting. How are you adding the SDK to your app? Are you using DLLs or NuGet?

**Comment by kvntzn** [comment]
@uerceg I added it using NuGet.

**Comment by kvntzn** [comment]
It worked when I build the app using VS2019 paired with a Mac. It seems like it only occurred when I am building using VS 2019 with Xamarin Hot Restart. Thanks anw.

**Comment by uerceg** [comment]
@kvntzn Thanks for the update (and sorry for delayed reply). Very interesting finding, we'll keep our eyes on it. Cheers!
