### ISSUE TITLE
Sandbox/Production "flag" possible not working

### ISSUE THREAD

**Issue by balivo** [adjust/xamarin_sdk#31]
Hi,

I'm facing an issue with the lastest Xamarin SDK on Android and iOS.

I startup Adjust SDK using:

Android:

//Adjust
            var config = new AdjustConfig(
                p0: this,
                p1: Constants.AdjustAppToken,
                p2: Constants.AdjustEnvironment);
            Adjust.OnCreate(config);

iOS:

//Adjust
                var config = ADJConfig.ConfigWithAppToken(
                    appToken: Constants.AdjustAppToken,
                    environment: Constants.AdjustEnvironment);
                Adjust.AppDidLaunch(config);

"Constants.AdjustEnvironment" are "sandbox" or "production".

The problem is, when I use "production", the data is tracked on "sandbox" env, and not on "production".

Previously, I have an issue with "AdjustConfig.EnvironmentProduction" and "AdjustConfig.EnvironmentSandbox" constants always returning NULL on Android and iOS.

Any suggestion?

**Comment by uerceg** [comment]
Hi @balivo 

Thanks for reporting this. Not sure if it's exactly the same issue, but are you using also environment described in [this issue](https://github.com/adjust/xamarin_sdk/issues/30)?

**Comment by balivo** [comment]
Hi @uerceg is not related...

Because is not in debug mode, is after release.

**Comment by uerceg** [comment]
Hi @balivo 

We were trying to reproduce the issue you were mentioning, but no luck. Whenever we attempt to assign **AdjustConfig.EnvironmentProduction** or **AdjustConfig.EnvironmentSandbox** to some string variable, it always translates to **"production"** and **"sandbox"** values. 

<img width="779" alt="Screenshot 2020-12-09 at 23 16 01" src="https://user-images.githubusercontent.com/1741635/101695555-0f776680-3a75-11eb-9185-ae6970120fe9.png">

How does your development environment look like? Are you developing on Windows/Mac? How are you adding our SDK to your app (DLLs or maybe NuGet)?

Also that sounds pretty weird that usage of string constants is pointing your traffic to different environment. We just tested this and it sends traffic properly to sandbox/production on both, iOS and Android platforms.

Can you make a test run with setting environment manually to **"sandbox"** and **"production"** environments and send logs over from those runs? Feel free to omit any sensitive information from logs.

**Comment by balivo** [comment]
I manually set the environment to "sandbox" and "production" BUT not working in debug mode (with VS connected).

All the time I call:
var config = ADJConfig.ConfigWithAppToken(
appToken: "MY_TOKEN",
environment: "sandbox_or_production");
Adjust.AppDidLaunch(config);

The "config" variable is null... No logs at output too...

**Comment by uerceg** [comment]
Hi @balivo 

That's pretty weird. Can you reproduce this in pretty basic sample Xamarin app to send us over to check? We are absolutely unable to reproduce this on our end.

**Comment by uerceg** [comment]
HI @balivo 

Any update on this one?

Cheers

**Comment by uerceg** [comment]
In case you need any further assistance on this one, feel free to reopen/comment. Cheers.
